### ISSUE TITLE
Conflicting documentation

### ISSUE THREAD

**Issue by TheodorGosden** [sassoftware/python-dlpy#73]
`model.deploy` has a server-side param as path, but if you look at the code, it will go down and pick .save_to_astore, which has a client-side param as path.

**Comment by yg2288** [comment]
This was just addressed in #53, which updated the doc to specify client-side path.  However, note that for deploy to 'table', the path will still be server-side.

**Comment by ethem-kinginthenorth** [comment]
@yg2288 I just merged your last pull, does that resolve this issue?

**Comment by yg2288** [comment]
I think we can close this, Wenyu recently resolved the issue. Thanks

**Comment by ethem-kinginthenorth** [comment]
@TheodorGosden can you check if the documentation is clear now?

**Comment by TheodorGosden** [comment]
@ethem-kinginthenorth I'm still getting the same documentation on https://sassoftware.github.io/python-dlpy/generated/dlpy.model.Model.deploy.html

It's mostly because that astore is the default option, so i'd expect the docs to say client side.

**Comment by ethem-kinginthenorth** [comment]
I think I know the reason. IF we don't do a release, auto-generated docs are the same. I am hoping to do another release this week, so it should be better. Meanwhile, maybe you want to check the source code to see if the documentation there is better as it will be generated when we do the release. Thanks

**Comment by TheodorGosden** [comment]
Looks good in the source code 👍 Closing issue.
